version: '3'
services:
  bot:
    container_name: bot-container
    build: ./bot
    entrypoint: python bot.py
    env_file:
      - ./bot/.env
    ports:
      - '3000:3000'
  api:
    container_name: api-container
    build: ./api
    entrypoint: python app.py
    env_file:
      - ./api/.env
    ports:
      - '5000:5000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"